apiVersion: apps/v1
kind: Deployment
metadata:
  name: saloon
  labels:
    app: saloon

spec:
  replicas: 2

  selector:
    matchLabels:
      app: saloon

  template:
    metadata:
      labels:
        app: saloon

    spec:
      containers:
        - name: saloon
          image: srinivasu56/saloon:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
